FROM node:18.20.1-alpine3.18

WORKDIR /app

RUN apk --no-cache --update add bash

ADD resources/netstats-dashboard/ ./

RUN npm install

RUN npm install -g grunt-cli

RUN grunt

# Entrypoints
ADD entrypoints/netstats-dashboard ./entrypoints
RUN chmod +x entrypoints/*