FROM hexpm/elixir:1.13.1-erlang-24.1.3-alpine-3.16.0

WORKDIR /app

RUN apk --no-cache --update add alpine-sdk gmp-dev automake autoconf libtool inotify-tools bash nodejs npm

RUN apk --update add curl ca-certificates git

# Get Rust
RUN curl --proto '=https' --tlsv1.2 https://sh.rustup.rs -sSf | sh -s -- -y
RUN echo 'source $HOME/.cargo/env' >> $HOME/.bashrc
ENV PATH="/root/.cargo/bin:${PATH}" \
    RUSTFLAGS="-C target-feature=-crt-static" \
    MIX_ENV="prod"
# SHELL [ "/bin/sh", "-s", ".", "$HOME/.cargo/env" ]

# # Cache elixir deps
ADD resources/blockscout-4.1.8-beta/mix.exs ./blockscout-4.1.8-beta/mix.lock ./
ADD resources/blockscout-4.1.8-beta/apps/block_scout_web/mix.exs ./apps/block_scout_web/
ADD resources/blockscout-4.1.8-beta/apps/explorer/mix.exs ./apps/explorer/
ADD resources/blockscout-4.1.8-beta/apps/ethereum_jsonrpc/mix.exs ./apps/ethereum_jsonrpc/
ADD resources/blockscout-4.1.8-beta/apps/indexer/mix.exs ./apps/indexer/

ENV MIX_HOME=/opt/mix
RUN mix local.hex --force
# RUN mix deps.update libsecp256k1
RUN mix do deps.get, local.rebar --force, deps.compile, compile

ADD resources/blockscout-4.1.8-beta/apps ./apps
ADD resources/blockscout-4.1.8-beta/config ./config
ADD resources/blockscout-4.1.8-beta/rel ./rel
ADD resources/blockscout-4.1.8-beta/*.exs ./

# Run forderground build and phoenix digest
RUN mix compile && npm install npm@latest

# Add blockscout npm deps
RUN cd apps/block_scout_web/assets/ && \
    npm install && \
    npm run deploy && \
    cd /app/apps/explorer/ && \
    npm install

RUN mix phx.digest

# Entrypoints
ADD entrypoints/explorer ./entrypoints
RUN chmod +x entrypoints/*