FROM node:18.20.1-alpine3.18

WORKDIR /app

RUN apk --no-cache --update add bash

ADD resources/netstats-api/ ./

RUN npm install

# Entrypoints
ADD entrypoints/netstats-dashboard ./entrypoints
RUN chmod +x entrypoints/*