[Eth]
NetworkId = 62165
SyncMode = "full"

[Node]
HTTPHost = "localhost"
HTTPPort = 3545
HTTPVirtualHosts = ["localhost"]
HTTPModules = ["personal", "eth", "net", "web3", "admin", "miner", "txpool", "debug"]
AuthAddr = "localhost"
AuthPort = 8551
AuthVirtualHosts = ["localhost"]
WSHost = "localhost"
WSPort = 3546
WSModules = ["personal", "eth", "net", "web3", "admin", "miner", "txpool", "debug"]
GraphQLVirtualHosts = ["localhost"]


[Node.P2P]
MaxPeers = 200
NoDiscovery = false
BootstrapNodes = ["enode://daf35b13c15d62766ebd313a2798923a2c83b78110f547570a153f89546cca58508cb7d5c79aafbddd6c09faba56b8e0d0a8332d38576ac8896292fa2f06afc3@202.143.109.43:40606"]
StaticNodes = []
TrustedNodes = []
ListenAddr = ":40605"